# Generated by Django 5.1.6 on 2025-05-29 02:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPNConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('config_file', models.FileField(upload_to='configs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
